---
-  name: install apache2 and php
   hosts: all
   become: yes
   tasks: 
     - name: install apache2
       ansible.builtin.apt:
         name: apache2
         state: present
         update_cache: yes 
     - name: install apache2 and php
       ansible.builtin.apt: 
         pkg:
         - php
         - libapache2-mod-php
         - php-mysql -y  
         state: present
     - name: php copy
       ansible.builtin.copy:
         src: info.php+
         dest: /var/www/html/info.php
     - name: restart apache
       ansible.builtin.systemd:
         name: apache2
         state: started
         enabled: yes

             



