apiVersion: v1
kind: Pod 
metadata:
  name: nginx
spec:
  containers:
    - image: nginx:latest
      name: nginx-container
      ports:
        - containerPort: 80
          protocol: TCP
    - image: jenkins/jenkins:lts-jdk11
      name: jenkins
      ports:
        - containerPort: 8080
          protocol: TCP      

         